// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KazanlakRun.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250702141005_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AidStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aid stationn 1",
                            ShortName = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aid stationn 2",
                            ShortName = "A2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aid stationn 3",
                            ShortName = "A3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aid stationn 4",
                            ShortName = "A4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aid stationn 5",
                            ShortName = "A5"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStationDistance", b =>
                {
                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<int>("DistanceId")
                        .HasColumnType("int");

                    b.HasKey("AidStationId", "DistanceId");

                    b.HasIndex("DistanceId");

                    b.ToTable("AidStationDistances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Distans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegRunners")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Distances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AidStationId");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Table",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Chair",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Tent",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 4,
                            AidStationId = 2,
                            Measure = "pcs",
                            Name = "Plates",
                            Quantity = 40
                        },
                        new
                        {
                            Id = 5,
                            AidStationId = 2,
                            Measure = "pcs",
                            Name = "Cups",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 6,
                            AidStationId = 2,
                            Measure = "kg",
                            Name = "Salt",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            AidStationId = 3,
                            Measure = "l",
                            Name = "Drinking water",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 8,
                            AidStationId = 3,
                            Measure = "l",
                            Name = "Isotonic",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            AidStationId = 3,
                            Measure = "pcs",
                            Name = "Lemons",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 10,
                            AidStationId = 4,
                            Measure = "kg",
                            Name = "Apples",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            AidStationId = 4,
                            Measure = "pcs",
                            Name = "Bananas",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            AidStationId = 4,
                            Measure = "pcs",
                            Name = "Chocolate",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 13,
                            AidStationId = 5,
                            Measure = "bottles",
                            Name = "Soap",
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "doctor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "security"
                        },
                        new
                        {
                            Id = 3,
                            Name = "radio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "food preparation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "time recorder"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AidStationId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AidStationId = 1,
                            Email = "nnnnnn@nnn.bg",
                            Names = "Nikola Nikolov",
                            Phone = "0888998899"
                        },
                        new
                        {
                            Id = 2,
                            AidStationId = 2,
                            Email = "iiiiii@.iii.bg",
                            Names = "Ivan Ivanov",
                            Phone = "0888999999"
                        },
                        new
                        {
                            Id = 3,
                            AidStationId = 3,
                            Email = "gggggg@ggg.bg",
                            Names = "Georg Georgiev",
                            Phone = "0888777777"
                        },
                        new
                        {
                            Id = 4,
                            AidStationId = 1,
                            Email = "petarp@p.bg",
                            Names = "Petar Petrov",
                            Phone = "0888111111"
                        },
                        new
                        {
                            Id = 5,
                            AidStationId = 2,
                            Email = "maria@i.bg",
                            Names = "Maria Ivanova",
                            Phone = "0888222222"
                        },
                        new
                        {
                            Id = 6,
                            AidStationId = 3,
                            Email = "stoyand@d.bg",
                            Names = "Stoyan Dimitrov",
                            Phone = "0888333333"
                        },
                        new
                        {
                            Id = 7,
                            AidStationId = 4,
                            Email = "elena@p.bg",
                            Names = "Elena Petrova",
                            Phone = "0888444444"
                        },
                        new
                        {
                            Id = 8,
                            AidStationId = 5,
                            Email = "vlad@st.bg",
                            Names = "Vladimir Stoyanov",
                            Phone = "0888555555"
                        },
                        new
                        {
                            Id = 9,
                            AidStationId = 1,
                            Email = "tsveta@k.bg",
                            Names = "Tsveta Koleva",
                            Phone = "0888666666"
                        },
                        new
                        {
                            Id = 10,
                            AidStationId = 2,
                            Email = "nikolay@m.bg",
                            Names = "Nikolay Marinov",
                            Phone = "0888778778"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.VolunteerRole", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("VolunteerRoles");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStationDistance", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("AidStationDistances")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KazanlakRun.Data.Models.Distance", "Distance")
                        .WithMany("AidStationDistances")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Good", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("Goods")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("Volunteers")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.VolunteerRole", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.Role", "Role")
                        .WithMany("VolunteerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KazanlakRun.Data.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerRoles")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStation", b =>
                {
                    b.Navigation("AidStationDistances");

                    b.Navigation("Goods");

                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Distance", b =>
                {
                    b.Navigation("AidStationDistances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Role", b =>
                {
                    b.Navigation("VolunteerRoles");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.Navigation("VolunteerRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
