// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KazanlakRun.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250703160527_UserId_in_Volunters")]
    partial class UserId_in_Volunters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AidStations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Aid stationn 1",
                            ShortName = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aid stationn 2",
                            ShortName = "A2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aid stationn 3",
                            ShortName = "A3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Aid stationn 4",
                            ShortName = "A4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Aid stationn 5",
                            ShortName = "A5"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStationDistance", b =>
                {
                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<int>("DistanceId")
                        .HasColumnType("int");

                    b.HasKey("AidStationId", "DistanceId");

                    b.HasIndex("DistanceId");

                    b.ToTable("AidStationDistances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Distance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Distans")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegRunners")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Distances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<string>("Measure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AidStationId");

                    b.ToTable("Goods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Table",
                            Quantity = 10
                        },
                        new
                        {
                            Id = 2,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Chair",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            AidStationId = 1,
                            Measure = "pcs",
                            Name = "Tent",
                            Quantity = 7
                        },
                        new
                        {
                            Id = 4,
                            AidStationId = 2,
                            Measure = "pcs",
                            Name = "Plates",
                            Quantity = 40
                        },
                        new
                        {
                            Id = 5,
                            AidStationId = 2,
                            Measure = "pcs",
                            Name = "Cups",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 6,
                            AidStationId = 2,
                            Measure = "kg",
                            Name = "Salt",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 7,
                            AidStationId = 3,
                            Measure = "l",
                            Name = "Drinking water",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 8,
                            AidStationId = 3,
                            Measure = "l",
                            Name = "Isotonic",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 9,
                            AidStationId = 3,
                            Measure = "pcs",
                            Name = "Lemons",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 10,
                            AidStationId = 4,
                            Measure = "kg",
                            Name = "Apples",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 11,
                            AidStationId = 4,
                            Measure = "pcs",
                            Name = "Bananas",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 12,
                            AidStationId = 4,
                            Measure = "pcs",
                            Name = "Chocolate",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 13,
                            AidStationId = 5,
                            Measure = "bottles",
                            Name = "Soap",
                            Quantity = 10
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "doctor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "security"
                        },
                        new
                        {
                            Id = 3,
                            Name = "radio"
                        },
                        new
                        {
                            Id = 4,
                            Name = "food preparation"
                        },
                        new
                        {
                            Id = 5,
                            Name = "time recorder"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AidStationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AidStationId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AidStationId = 1,
                            Email = "nnnnnn@nnn.bg",
                            Names = "Nikola Nikolov",
                            Phone = "0888998899"
                        },
                        new
                        {
                            Id = 2,
                            AidStationId = 2,
                            Email = "iiiiii@.iii.bg",
                            Names = "Ivan Ivanov",
                            Phone = "0888999999"
                        },
                        new
                        {
                            Id = 3,
                            AidStationId = 3,
                            Email = "gggggg@ggg.bg",
                            Names = "Georg Georgiev",
                            Phone = "0888777777"
                        },
                        new
                        {
                            Id = 4,
                            AidStationId = 1,
                            Email = "petarp@p.bg",
                            Names = "Petar Petrov",
                            Phone = "0888111111"
                        },
                        new
                        {
                            Id = 5,
                            AidStationId = 2,
                            Email = "maria@i.bg",
                            Names = "Maria Ivanova",
                            Phone = "0888222222"
                        },
                        new
                        {
                            Id = 6,
                            AidStationId = 3,
                            Email = "stoyand@d.bg",
                            Names = "Stoyan Dimitrov",
                            Phone = "0888333333"
                        },
                        new
                        {
                            Id = 7,
                            AidStationId = 4,
                            Email = "elena@p.bg",
                            Names = "Elena Petrova",
                            Phone = "0888444444"
                        },
                        new
                        {
                            Id = 8,
                            AidStationId = 5,
                            Email = "vlad@st.bg",
                            Names = "Vladimir Stoyanov",
                            Phone = "0888555555"
                        },
                        new
                        {
                            Id = 9,
                            AidStationId = 1,
                            Email = "tsveta@k.bg",
                            Names = "Tsveta Koleva",
                            Phone = "0888666666"
                        },
                        new
                        {
                            Id = 10,
                            AidStationId = 2,
                            Email = "nikolay@m.bg",
                            Names = "Nikolay Marinov",
                            Phone = "0888778778"
                        });
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.VolunteerRole", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("VolunteerId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("VolunteerRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-e5f6-4782-8209-d76562e0feaa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "f1e2d3c4-b5a6-4948-9309-c56782b0faab",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9669f490-4089-4f7f-8b74-2d2d15e23c23",
                            Email = "admin@KazanlakRun.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@KAZANLAKRUN.COM",
                            NormalizedUserName = "ADMIN@KAZANLAKRUN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHrTreRyJpsZKTJwg+x4lgQFNyJQbAjpreP4Q4UZe0cpceMtje4OJxajkRAy1ZzbsA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "62afd5fb-7539-4d65-9fdb-3cb5813ca079",
                            TwoFactorEnabled = false,
                            UserName = "admin@KazanlakRun.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7699db7d-964f-4782-8209-d76562e0fece",
                            RoleId = "a1b2c3d4-e5f6-4782-8209-d76562e0feaa"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStationDistance", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("AidStationDistances")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KazanlakRun.Data.Models.Distance", "Distance")
                        .WithMany("AidStationDistances")
                        .HasForeignKey("DistanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");

                    b.Navigation("Distance");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Good", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("Goods")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.AidStation", "AidStation")
                        .WithMany("Volunteers")
                        .HasForeignKey("AidStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AidStation");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.VolunteerRole", b =>
                {
                    b.HasOne("KazanlakRun.Data.Models.Role", "Role")
                        .WithMany("VolunteerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KazanlakRun.Data.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerRoles")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.AidStation", b =>
                {
                    b.Navigation("AidStationDistances");

                    b.Navigation("Goods");

                    b.Navigation("Volunteers");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Distance", b =>
                {
                    b.Navigation("AidStationDistances");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Role", b =>
                {
                    b.Navigation("VolunteerRoles");
                });

            modelBuilder.Entity("KazanlakRun.Data.Models.Volunteer", b =>
                {
                    b.Navigation("VolunteerRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
