services:
  - type: web
    name: kazanlak-run
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://*:$PORT
    buildCommand: ""
    startCommand: ""